alias: pilar_sa_dw
description: ''
trigger:
  platform: numeric_state
  entity_id: sensor.salon_dw_battery
  below: '10'
condition: []
action:
  - service: notify.mail
    data:
      title: Pilar puerta principal !!
      message: Cambiar pilar puerta principal pronto.
      target:
        - "jancasacondor@gmail.com"
mode: single
