alias: Battery door
description: ''
trigger:
  platform: numeric_state
  entity_id: sensor.shelly_door_battery
  below: '10'
condition: []
action:
  - service: notify.mail
    data:
      title: Pilar puerta casa !!
      message: Cambiar pilar puerta casa pronto.
      target:
        - "jancasacondor@gmail.com"
mode: single
