alias: Alert HA
description: ''
trigger:
  - platform: state
    entity_id: binary_sensor.ha_server
    from: 'on'
    to: 'off'
    for:
      minutes: 10
condition: []
action:
  - service: notify.mail
    data:
      title: Internet not reachable
      message: Power/Internet is down!
      target:
        - "jancasacondor@gmail.com"
mode: single
