#
# configuration.yaml is the top level configuration,
# and contains only references to directories with actual configuration files.
#
homeassistant:
  auth_providers:
    - type: trusted_networks
      trusted_networks:
        - 192.168.10.0/24
        - 192.168.20.0/24
      allow_bypass_login: true
    - type: homeassistant
  packages:
    common: !include_dir_merge_named common.config/integrations
    setup: !include_dir_merge_named active/integrations
  customize: !include_dir_merge_named common.config/customizations

automation common: !include_dir_list common.config/automations
automation setup: !include_dir_list active/automations
scene: !include_dir_list common.config/scenes
binary_sensor: !include_dir_list active/entities/binary_sensors
