---
#
# https://www.home-assistant.io/integrations/default_config
#
#default_config:

automation:

#backup:

bluetooth:

#config:

counter:

#dhcp:

energy:

frontend:

#hardware:

history:

homeassistant_alerts:

#cloud:

image_upload:

input_boolean:

input_button:

input_datetime:

input_number:

input_select:

input_text:

#logbook:
#logger:

map:

#media_source:

mobile_app:

#my:

person:

schedule:

scene:

script:

#ssdp:
#stream:

sun:

system_health:

#tag:
#timer:
#usb:
#webhook:

zeroconf:

#zone:
