alias: Battery WH65
description: ''
trigger:
- type: bat_low
  platform: device
  device_id: caefc01de2902e749923315a18297717
  entity_id: binary_sensor.wh2650a_wh65_battery
  domain: binary_sensor
condition: []
action:
  - service: notify.mail
    data:
      title: Pilar WH65 !!
      message: Cambiar pilar external WH casa pronto.
      target:
        - "jancasacondori@gmail.com"
mode: single
