alias: Battery WH25
description: ''
trigger:
- type: bat_low
  platform: device
  device_id: caefc01de2902e749923315a18297717
  entity_id: binary_sensor.wh2650a_wh25_battery
  domain: binary_sensor
condition: []
action:
  - service: notify.mail
    data:
      title: Pilar WH25 casa !!
      message: Cambiar pilar WH25 casa pronto.
      target:
        - "jancasacondor@gmail.com"
mode: single
