alias: Flood deposit
description: ''
trigger:
- type: moist
  platform: device
  device_id: d6b7a92a1c3471c0fbc2bd38bfe709f5
  entity_id: binary_sensor.shelly_flood_flood
  domain: binary_sensor
condition: []
action:
  - service: notify.mail
    data:
      title: deposito sale agua !!
      message: Cerrar entrada de agua y limpiar.
      target:
        - "jancasacondor@gmail.com"
mode: single
