#
# https://www.home-assistant.io/integrations/default_config
#
#default_config:
#backup:
#config:
#dhcp:
#hardware:
#cloud:
#logbook:
#logger:
#media_source:
#my:
#ssdp:
#stream:
#tag:
#timer:
#usb:
#webhook:
#zone:

automation:
bluetooth:
counter:
energy:
frontend:
history:
homeassistant_alerts:
image_upload:
input_boolean:
input_button:
input_datetime:
input_number:
input_select:
input_text:
map:
mobile_app:
person:
schedule:
scene:
script:
sun:
system_health:
zeroconf:

